name: multiple-event-workflow
on:
  push:
  issues:
    types: [opend]
  workflow_dispatch:

jobs:
  multiple-event-job:
    runs-on: ubuntu-latest
    steps:
    - name: step1
      run: echo hello world
